html_language: "de"
html_dir: "ltr"

microsite_cname: "patterns-de.sociocracy30.org"

target_filename: "S3-Praxisleitfaden"

pattern_prefix: " Muster %(chapter)s.%(section)s:"

version: "v2018-03-21-de-1.0"