title: Soziokratie 3.0 Praxisleitfaden
email: bernhard.bockelbrink@gmail.com
description:
  The official description of Sociocracy 3.0: Alle Muster, die sieben Prinzipien und alle wichtigen Konzepte in Soziokratie 3.0, von Bernhard Bockelbrink, James Priest und Liliana David.
baseurl: ""
url: "http://s3-working-group.github.io"
twitter_username: sociocracy30
source:   .
destination:  ./_site
layouts_dir:  ./_layouts
includes_dir:  ./_includes
markdown: kramdown
safe: true
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
exclude:
  _export
  _python
  _templates

