# Site settings
title: Soziokratie 3.0 - Ein Praxisleitfaden
email: bernhard.bockelbrink@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Die offizielle Dokumentation zu Soziokratie 3.0 — mit allen Muster, den sieben Prinzipien und allen wichtigen Konzepten, von Bernhard Bockelbrink, James Priest und Liliana David.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://patterns-de.sociocracy30.org" # the base hostname & protocol for your site

twitter_username: sociocracy30

# Build settings
source:   .
destination:  ./_site
layouts_dir:  ./_layouts
includes_dir: ./_includes


markdown: kramdown
safe: true # required on Github pages (no plugins)

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page" # overrides previous default layout


exclude:      [
  "_export",
  "_python",
  "_templates",
  ]
